In [1]:
import numpy as np

In [10]:
# Criando um array de 1 a 10
array1 = np.arange(1, 11)
print("Array de 10:", array1)

Array de 10: [ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# Criando um array de 0
array2 = np.zeros(10)
print("Array de zeros:", array2)

Array de zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
# criando um linspace de 10 valores entre 0 e 50
array_linspace = np.linspace(0, 50, 10)
print("Array linspace de 0 a 50 com 10 valores:", array_linspace)

Array linspace de 0 a 50 com 10 valores: [ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [32]:
# Criando uma matriz identidade 3x3
matriz_identidade = np.eye(3)
print("Matriz identidade 3x3:\n", matriz_identidade)

Matriz identidade 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
# Indexação e fatiamento
arr = np.arange(10, 70, 10)
fatiando = arr[:3]
fatiando

array([10, 20, 30])

In [43]:
# Calculando o quadrado dos números de 1 a 5
arr_quadrado = np.arange(1, 6) ** 2
arr_quadrado

array([ 1,  4,  9, 16, 25])

In [51]:
# Soma de arrays
arr_a = np.arange(1, 4)
arr_b = np.arange(4, 7)

array_soma = arr_a + arr_b
array_soma

array([5, 7, 9])

In [52]:
# Transformando um array de 10 em matriz 3x3
arr_reshape = np.arange(1, 10).reshape(3, 3)
arr_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
# Criando um array 4x4 com valores aleatórios entre 0 e 1
arr_random = np.random.rand(4, 4)
arr_random

array([[0.07893958, 0.78507143, 0.41274317, 0.38671826],
       [0.83696357, 0.96418522, 0.12771733, 0.34181461],
       [0.82750843, 0.97851892, 0.10329683, 0.44966734],
       [0.59571401, 0.78930437, 0.17666102, 0.99342843]])