In [2]:
import numpy as np

In [6]:
np

<module 'numpy' from 'c:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>

In [4]:
minha_lista = [1, 2, 3]

In [5]:
np.array(minha_lista)

array([1, 2, 3])

In [8]:
minha_matriz = [[1, 2, 3], [4, 5, 6]]

In [9]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
sum(minha_lista)

6

In [12]:
np.sum(minha_matriz)

21

In [13]:
matriz_numpy = np.array(minha_matriz)

In [14]:
np.sum(matriz_numpy)

21

In [22]:
np.arange(0, 1000, 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [ ]:
# Função Numpy para criar arrays com 0's
np.zeros(3)

array([0., 0., 0.])

In [ ]:
# 2 dimensões
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 3 dimensões
np.zeros([3, 3, 3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Função Numpy para criar Arrays com 1's
np.ones([1, 3])

array([[1., 1., 1.]])

In [27]:
# Matriz identidade
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.linspace(0, 100, 50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [76]:
np.random.random(5)

array([0.97677299, 0.73191406, 0.90326203, 0.04928605, 0.44340494])

In [85]:
np.random.random(5) * 100

array([23.91153449, 31.32925697, 72.92160427, 32.865752  , 84.34818397])

In [88]:
np.random.random([2, 5]) * 100

array([[27.58519958, 28.83386799, 59.18402776, 77.53012869, 89.41240078],
       [45.94932114, 78.07430717, 54.73753933, 30.49644579, 85.84563729]])

In [90]:
array = np.zeros(4)

In [92]:
array.shape

(4,)

In [93]:
array.reshape([2, 2])

array([[0., 0.],
       [0., 0.]])

In [94]:
array = np.random.random(10)

In [95]:
array

array([0.84790521, 0.39894897, 0.0585959 , 0.11287741, 0.12953996,
       0.05907597, 0.72726785, 0.72392378, 0.0831622 , 0.38877206])

In [96]:
array.max()

0.847905214323168

In [97]:
array.min()

0.058595904385571496