In [1]:
import numpy as np

In [3]:
array1 = np.arange(0, 100, 10)
array2 = np.arange(0, 50, 5)


In [4]:
array1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
array2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [6]:
array1 + array2

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135])

In [7]:
array1 - array2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
array1 * array2

array([   0,   50,  200,  450,  800, 1250, 1800, 2450, 3200, 4050])

In [9]:
array1 / array2

C:\Users\Windows\AppData\Local\Temp\ipykernel_22812\1862955035.py:1: RuntimeWarning: invalid value encountered in divide
  array1 / array2


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [10]:
0 / 0

ZeroDivisionError: division by zero

In [11]:
array1 ** 2

array([   0,  100,  400,  900, 1600, 2500, 3600, 4900, 6400, 8100])

In [12]:
array1 * 100

array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000])

In [13]:
np.sqrt(array1)

array([0.        , 3.16227766, 4.47213595, 5.47722558, 6.32455532,
       7.07106781, 7.74596669, 8.36660027, 8.94427191, 9.48683298])