# Indexação e Fatiamento de Arrays

In [2]:
import numpy as np

In [4]:
array = np.arange(0, 30, 3)

In [5]:
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
array[3]

9

In [7]:
array[0:2]

array([0, 3])

In [8]:
array[:5]

array([ 0,  3,  6,  9, 12])

In [9]:
array[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
array[[0, 5]]

array([ 0, 15])

In [11]:
array[4:7]

array([12, 15, 18])

In [12]:
array[5:] = 100

In [13]:
array

array([  0,   3,   6,   9,  12, 100, 100, 100, 100, 100])

In [ ]:
#.arange faz o array e .reshape faz linha x coluna
array_2d = np.arange(50).reshape([5,10])

In [17]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
array_2d[0:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
array_2d[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [22]:
array_2d[0:3, 4:]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [23]:
array_2d > 20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [28]:
booleano = array_2d > 20

In [29]:
array_2d[booleano]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
np.logical_and(array_2d >= 20, array_2d <= 30)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [31]:
booleano = np.logical_and(array_2d >= 20, array_2d <= 30)

In [33]:
array_2d[booleano]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
np.logical_or(array_2d >= 20, array_2d <= 10)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])